server:
  port: 8080
spring:
  application:
    name: synchro-bank
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/synchrobankdb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false

job-cron-notifications-exec: "0 */1 * * * *"