server:
  port: 1080
spring:
  datasource:
    url: jdbc:postgresql://localhost:1032/synchro-bank-database
    username: synchro-bank-user
    password: synchro-bank-password
  jpa:
    hibernate:
      ddl-auto: validate