name: Check

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  commitlint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install commitlint
        run: |
          npm install @commitlint/cli @commitlint/config-conventional
          echo "module.exports = { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js
        # For a cleaner setup, consider adding these dev dependencies to a package.json file.

      - name: Validate PR commit messages
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Validate last commit message on push
        if: github.event_name == 'push'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose

  buildAndSonar:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build Workflow
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: Build-app-workflow
          token: ${{ secrets.USER_GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          wait-for-completion: true
          display-workflow-run-url: true
          display-workflow-run-url-timeout: 10m
          display-workflow-run-url-interval: 15s
          wait-for-completion-timeout: 10m
          wait-for-completion-interval: 15s